// src/ui/strings.ts — Textos de la interfaz (español, Perú). Regla R-12: TODOS los textos visibles aquí.
//
// Principio de diseño (contexto §25.6): "MENOS TEXTO, MÁS ESTADO Y ACCIÓN". Títulos cortos, etiquetas
// de estado y botones. Nada de explicaciones técnicas, fases, tareas T-XX ni mensajes para desarrolladores.

import type {
  CameraLinkStatus,
  CaptureMode,
  DeviceRole,
  IncidentType,
  LateralCode,
  PassStatus,
  QualityStatus,
  SequenceStatus,
  SessionStatus,
  SlotOutcome,
} from '../domain/types';

export const S = {
  appName: 'Riachuelo Monitoreo',
  company: 'Agrícola Riachuelo',
  preparing: 'Preparando…',
  pending: 'Pendiente',
  loading: 'Cargando…',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  continue: 'Continuar',
  back: 'Volver',
  save: 'Guardar',
  close: 'Cerrar',
  retry: 'Reintentar',
  yes: 'Sí',
  no: 'No',
  none: '—',
  online: 'Con internet',
  offline: 'Sin internet',
  version: 'Versión',

  // ------------------------------------------------ autenticación
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Monitoreo fitosanitario de vid',
    email: 'Correo',
    password: 'Contraseña',
    show: 'Mostrar',
    hide: 'Ocultar',
    submit: 'Ingresar',
    createAccount: 'Crear cuenta',
    forgot: '¿Olvidaste tu contraseña?',
    preparingOffline: 'Preparando acceso sin internet…',
    lockedUntil: (time: string) => `Bloqueado hasta las ${time}`,
    required: 'Completa correo y contraseña.',
    demoHint: 'Cuentas de prueba',
  },
  register: {
    title: 'Crear cuenta',
    fullName: 'Nombre completo',
    email: 'Correo',
    phone: 'Celular (opcional)',
    employeeCode: 'Código de trabajador (opcional)',
    password: 'Contraseña',
    confirm: 'Confirmar contraseña',
    privacy:
      'Tus datos (nombre, correo y celular) se usan solo para identificarte en el sistema de monitoreo de Agrícola Riachuelo. Las cámaras fotografían la vegetación; evita fotografiar personas.',
    accept: 'Acepto el aviso de privacidad',
    submit: 'Enviar solicitud',
  },
  pendingScreen: {
    title: 'Solicitud enviada',
    body: 'Tu cuenta quedó pendiente de aprobación. El administrador te avisará cuando esté activa.',
    back: 'Volver a iniciar sesión',
  },
  forgot: {
    title: 'Recuperar contraseña',
    email: 'Correo',
    submit: 'Enviar solicitud',
    invalidEmail: 'Escribe un correo válido.',
    neutral: 'Si el correo está registrado, el administrador recibirá tu solicitud y te dará una contraseña temporal.',
  },
  changePassword: {
    title: 'Cambiar contraseña',
    mandatory: 'Debes cambiar tu contraseña temporal.',
    current: 'Contraseña actual',
    next: 'Nueva contraseña',
    confirm: 'Confirmar nueva contraseña',
    done: 'Contraseña actualizada.',
    logout: 'Cerrar sesión',
    mismatch: 'Las contraseñas no coinciden.',
    sameAsCurrent: 'La nueva contraseña debe ser distinta de la actual.',
    rules: 'Mínimo 8 caracteres, con letras y números. Evita datos personales o contraseñas comunes.',
  },
  reauth: {
    title: 'Validar acceso',
    action: 'Validar',
    done: 'Acceso validado con internet.',
  },

  // ------------------------------------------------ función y permisos
  role: {
    title: 'Función del celular',
    useAs: (name: string) => `Usar como ${name}`,
    confirmTitle: 'Confirmar función',
    confirmBody: (name: string) => `Este celular quedará como ${name}.`,
    deviceData: 'Este equipo',
    model: 'Modelo',
    system: 'Sistema',
    descriptions: {
      CONTROLADOR: 'Crea la sesión, ordena las capturas y recibe las fotos.',
      CAMERA_1: 'Toma las fotos del lado izquierdo del soporte.',
      CAMERA_2: 'Toma las fotos del lado derecho del soporte.',
    } as Record<DeviceRole, string>,
    // Elección después del login (ADR 0005)
    prompt: '¿Qué función cumplirá este celular?',
    current: 'Actual',
    locked: 'Bloqueada',
    choose: 'Elige una función',
    needs: {
      CONTROLADOR: 'Necesita: ubicación y Wi-Fi',
      CAMERA_1: 'Necesita: cámara y Wi-Fi',
      CAMERA_2: 'Necesita: cámara y Wi-Fi',
    } as Record<DeviceRole, string>,
  },
  permissions: {
    title: 'Permisos',
    camera: 'Cámara',
    location: 'Ubicación',
    localNetwork: 'Red local',
    localNetworkHint: 'Ajustes › Riachuelo › Red local',
    grant: 'Conceder',
    openSettings: 'Abrir Ajustes',
    granted: 'Concedido',
    denied: 'Denegado',
    undetermined: 'Sin decidir',
    notVerifiable: 'Revisar en Ajustes',
  },

  // ------------------------------------------------ ajustes
  settings: {
    title: 'Ajustes',
    logout: 'Cerrar sesión',
    user: 'Usuario',
    access: 'Acceso',
    offlineUntil: 'Válido sin internet hasta',
    role: 'Función',
    appVersion: 'App',
    protocol: 'Protocolo',
    quality: 'Perfil de calidad',
    config: 'Configuración',
    env: 'Entorno',
    freeSpace: 'Espacio libre',
    battery: 'Batería',
    deviceId: 'Equipo',
    changePassword: 'Cambiar contraseña',
    changeRole: 'Cambiar función',
    retryTransfers: 'Reintentar transferencias con error',
    exportDiagnostics: 'Exportar diagnóstico',
    freeSpaceAction: 'Liberar espacio',
    sounds: 'Sonidos',
    haptics: 'Vibración',
    gallery: 'Fotos guardadas',
    logoutConfirm: '¿Cerrar tu sesión en este celular?',
    logoutConfirmOpenSession:
      'Hay una sesión de monitoreo abierta en este celular. Quedará guardada con todas sus fotos (la pasada en curso se pausa). Al volver a iniciar sesión podrás continuarla o cerrarla.',
    retried: (n: number) => `${n} foto(s) vuelven a la cola.`,
    exported: 'Diagnóstico listo para compartir.',
    server: 'Servidor',
    testConnection: 'Probar conexión',
    simulated: 'Simulado',
    insecure: 'Conexión sin cifrar (http)',
  },

  // ------------------------------------------------ controlador
  controller: {
    panelTitle: 'Controlador',
    readiness: 'Preparación',
    catalogs: 'Catálogos',
    battery: 'Batería',
    space: 'Espacio',
    gps: 'GPS',
    openSession: 'Sesión abierta',
    started: 'Inicio',
    noSession: 'Sin sesión abierta',
    newSession: 'Nueva sesión',
    continueSession: 'Continuar sesión',
    discardDraft: 'Descartar borrador',
    discardConfirm: '¿Descartar el borrador de sesión?',
    sync: 'Sincronizar',
    incidents: 'Incidencias',
    pendingSync: 'Por sincronizar',
    sessionsLabel: (n: number) => `${n} sesión(es)`,
    gallery: 'Fotos',
  },
  catalogs: {
    title: 'Catálogos',
    version: 'Versión',
    updatedAt: 'Actualizado',
    lots: 'Lotes',
    rows: 'Hileras',
    segments: 'Segmentos',
    markers: 'Marcadores',
    update: 'Actualizar',
    updated: 'Catálogos actualizados.',
    never: 'Sin descargar',
    empty: 'Sin lotes en el servidor',
  },
  newSession: {
    title: 'Nueva sesión',
    mode: 'Modo de captura',
    interval: 'Intervalo',
    create: 'Crear sesión',
    seconds: (ms: number) => `${Math.round(ms / 1000)} s`,
  },
  pairing: {
    title: 'Vincular cámaras',
    host: 'IP',
    ports: 'Puertos',
    manualIp: 'IP manual',
    applyIp: 'Usar IP',
    regenerate: 'Regenerar QR',
    release: (name: string) => `Liberar ${name}`,
    releaseConfirm: (name: string) => `¿Liberar ${name}? Deberás repetir la prueba corta.`,
    waiting: 'Esperando cámara',
    continue: 'Continuar',
    tools: 'Herramientas de prueba',
    dropCam: (name: string) => `Cortar ${name} 10 s`,
    forceBad: (name: string) => `Foto oscura en ${name}`,
  },
  shortTest: {
    title: 'Prueba corta',
    run: 'Ejecutar prueba',
    repeat: 'Repetir',
    response: 'Respuesta',
    quality: 'Calidad',
    transfer: 'Transferencia',
    time: 'Tiempo',
    offset: 'Desfase entre cámaras',
    passed: 'Aprobada',
    failed: 'Reprobada',
    running: 'En curso',
    notRun: 'Sin ejecutar',
    reason: 'Motivo',
    reasons: {
      SIN_RESPUESTA: 'La cámara no respondió a la orden',
      ERROR: 'La cámara respondió con un error',
      RESPUESTA_LENTA: (s: string, max: string) => `Respondió en ${s} (máximo ${max})`,
      ERROR_CAMARA: 'La cámara no pudo tomar la foto',
      FOTO_NO_LLEGO: 'La foto no llegó al controlador a tiempo',
      DEMASIADO_LENTA: (s: string, max: string) => `Tardó ${s} en total (máximo ${max})`,
      CALIDAD: 'La calidad de la foto no se pudo evaluar',
    },
  },
  newPass: {
    title: 'Nueva pasada',
    lot: 'Lote',
    row: 'Hilera',
    lateral: 'Lateral',
    segment: 'Segmento',
    marker: 'Marcador de inicio',
    start: 'Iniciar pasada',
    repeatLateral: 'Repetir lateral',
    repeatReason: 'Motivo de la repetición',
    pairing: 'Vincular cámaras',
    choose: 'Elegir',
    plants: (n: number) => `${n} plantas`,
  },
  pass: {
    title: 'Pasada activa',
    capture: 'CAPTURAR',
    pause: 'PAUSAR',
    resume: 'REANUDAR',
    changeMarker: 'CAMBIAR MARCADOR',
    endPass: 'TERMINAR PASADA',
    pairing: 'Vincular cámaras',
    retake: (cam: string, n: number) => `Repetir ${cam} (secuencia ${n})`,
    auto: 'Captura automática',
    autoActive: 'ACTIVA',
    autoPaused: 'PAUSADA',
    interval: 'Intervalo',
    marker: 'Marcador',
    segment: 'Segmento',
    complete: 'Completas',
    partial: 'Parciales',
    incomplete: 'Incompletas',
    total: 'Total',
    lastResult: 'Última',
    pendingFiles: 'Pendientes',
    offset: 'Desfase',
    noGps: 'Sin GPS',
    accuracy: (m: number) => `± ${Math.round(m)} m`,
    myGps: 'Tu GPS',
    stable: 'Quieta',
    moving: 'En movimiento',
  },
  marker: {
    title: 'Cambiar marcador',
    current: 'Actual',
    confirm: 'Confirmar',
    changed: (code: string) => `Marcador ${code}`,
  },
  closePass: {
    title: 'Terminar pasada',
    summary: 'Resumen',
    duration: 'Duración',
    retakes: 'Repeticiones',
    pendingTransfers: 'Fotos por llegar',
    incidents: 'Incidencias',
    status: 'Estado final',
    reason: 'Motivo (obligatorio si es incompleta)',
    close: 'Cerrar pasada',
    nextB: 'Crear LATERAL B',
    repeatLateral: 'Repetir lateral',
    otherRow: 'Otra hilera',
    pairing: 'Vincular cámaras',
    closeSession: 'Cerrar sesión de monitoreo',
    closed: 'Pasada cerrada.',
    bySegment: 'Por segmento',
  },
  sessionSummary: {
    title: 'Cerrar sesión de monitoreo',
    passes: 'Pasadas',
    missingPhotos: 'Fotos que faltan llegar',
    close: 'Cerrar sesión',
    wait: 'Esperar',
    closeAnyway: 'Cerrar igual',
    confirm: '¿Cerrar la sesión de monitoreo?',
    closed: 'Sesión cerrada.',
  },
  sync: {
    title: 'Sincronización',
    total: 'Total',
    sent: 'Enviados',
    pending: 'Pendientes',
    errors: 'Errores',
    lastAttempt: 'Último intento',
    syncNow: 'Sincronizar ahora',
    retryErrors: 'Reintentar errores',
    empty: 'Nada por sincronizar',
    stop: 'Detener',
    stopping: 'Deteniendo…',
    running: 'Sincronizando',
    server: 'Servidor',
    lastSync: 'Última sincronización',
    photos: 'Fotos',
    inCloud: 'En la nube',
    toConfirm: 'Por confirmar',
    withError: 'Con error',
    toUpload: 'Por subir',
    started: 'Inicio',
    status: 'Estado',
    review: 'Requieren revisión',
    more: (n: number) => `y ${n} más`,
    progress: (done: number, total: number) => `${done} de ${total}`,
    uploading: (sent: string, total: string) => `${sent} de ${total}`,
    needsOnline: 'Valida tu acceso con internet para sincronizar.',
    mobileDataTitle: 'Datos móviles',
    mobileDataBody: (size: string) => `Estás con datos móviles. Se enviarán unos ${size} de fotos. ¿Continuar?`,
    send: 'Enviar',
    step: {
      TICKET: 'Pidiendo permiso de subida',
      SUBIDA: 'Subiendo foto',
      CONFIRMACION: 'Confirmando',
    } as Record<'TICKET' | 'SUBIDA' | 'CONFIRMACION', string>,
    entity: {
      SESSION: 'Sesión',
      PASS: 'Pasada',
      SEQUENCE_BATCH: 'Secuencias',
      CAPTURE: 'Foto',
      INCIDENT_BATCH: 'Incidencias',
      SESSION_CLOSE: 'Cierre de sesión',
    } as Record<'SESSION' | 'PASS' | 'SEQUENCE_BATCH' | 'CAPTURE' | 'INCIDENT_BATCH' | 'SESSION_CLOSE', string>,
  },
  incidents: {
    title: 'Incidencias',
    add: 'Agregar incidencia',
    type: 'Tipo',
    severity: 'Severidad',
    detail: 'Detalle',
    empty: 'Sin incidencias',
    saved: 'Incidencia registrada.',
  },

  // ------------------------------------------------ cámaras
  camera: {
    scanTitle: 'Escanear QR',
    scanHint: 'Apunta al QR del controlador',
    retry: 'Reintentar',
    wifi: 'Wi-Fi',
    noWifi: 'Sin Wi-Fi',
    testMode: 'Modo prueba',
    liveTitle: 'Cámara en sesión',
    capturing: 'CAPTURANDO',
    connected: 'Conectada',
    connecting: 'Conectando…',
    disconnected: 'Sin conexión con el controlador — en pausa',
    rescan: 'Reescanear QR',
    abandon: 'Abandonar sesión',
    abandonConfirm: '¿Abandonar la sesión? Las fotos pendientes se conservan.',
    exit: 'Salir',
    retryTransfers: 'Reintentar transferencias con error',
    lastCapture: 'Última captura',
    pending: 'Pendientes',
    session: 'Sesión',
    lateral: 'Lateral',
    paused: 'EN PAUSA',
    waitingPass: 'Esperando pasada',
    otherSessionConfirm: 'Este celular está unido a otra sesión. ¿Cerrarla y unirse a la nueva?',
    testTitle: 'Prueba de cámara',
    takeTest: 'Tomar foto de prueba',
    autoMode: 'Automático',
    manualMode: 'Manual',
    autoHint: 'Dispara solo con la cámara quieta',
    stable: 'Quieta',
    moving: 'En movimiento',
    waitingStable: 'Esperando estabilidad…',
    metrics: 'Métricas',
    luminance: 'Luminancia',
    dark: 'Oscuros',
    bright: 'Saturados',
    sharpness: 'Nitidez',
    duration: 'Tiempo',
    noCameraPermission: 'Sin permiso de cámara',
  },

  // ------------------------------------------------ galería
  gallery: {
    title: 'Fotos guardadas',
    empty: 'Aún no hay fotos',
    filterAll: 'Todas',
    filterTest: 'Prueba',
    filterSession: 'Sesión',
    filterShort: 'Prueba corta',
    filterShortTab: 'Corta',
    deleteTest: 'Borrar fotos de prueba',
    deleteTestConfirm: '¿Borrar todas las fotos de prueba de este celular?',
    deleted: (n: number) => `${n} foto(s) borradas.`,
    share: 'Compartir',
    of: (i: number, n: number) => `${i} de ${n}`,
    cloud: {
      PENDIENTE_NUBE: 'Por subir',
      SUBIENDO: 'Subiendo',
      SINCRONIZADO: 'En la nube',
      ERROR_SINCRONIZACION: 'Error al subir',
    } as Record<'PENDIENTE_NUBE' | 'SUBIENDO' | 'SINCRONIZADO' | 'ERROR_SINCRONIZACION', string>,
  },

  // ------------------------------------------------ «Ubicar plaga» (ADR 0009)
  pests: {
    title: 'Ubicar plaga',
    entry: '🐞 Ubicar plaga',
    entryCount: (n: number) => `🐞 Ubicar plaga (${n})`,
    viewMap: 'Mapa',
    viewList: 'Lista',
    filterAll: 'Todas',
    filterConfirmed: 'Confirmadas',
    filterPossible: 'Posibles',
    refresh: 'Actualizar',
    updatedAt: (t: string) => `Actualizado ${t}`,
    neverUpdated: 'Sin descargar',
    empty: (days: number) => `No hay alertas de plaga en los últimos ${days} días.`,
    emptyFilter: 'No hay alertas con este filtro.',
    noLocation: 'Sin coordenadas',
    noLocationHint: 'Búscala por lote, hilera y plantas.',
    howToGo: 'Cómo llegar (Google Maps)',
    openInMaps: 'Ver punto en Google Maps',
    detail: 'Ver detalle',
    seeOnMap: 'Ver en el mapa',
    centerMe: '◎ Yo',
    fitAll: '⤢ Todo',
    baseSat: '🛰 Satélite',
    baseStreets: '🗺 Calles',
    allowLocation: 'Permitir ubicación',
    waitingGps: 'Buscando tu ubicación…',
    youAreThere: 'Estás en el lugar',
    distance: (d: string, dir: string) => `${d} al ${dir}`,
    accuracy: (m: number) => `± ${Math.round(m)} m`,
    myGps: 'Tu GPS',
    aiHint: (pct: number) => `Indicio de la IA: ${pct} %`,
    observation: 'Observación del especialista',
    place: 'Lugar',
    lot: 'Lote',
    row: 'Hilera',
    side: 'Lado',
    plants: 'Plantas',
    marker: 'Marcador',
    capturedAt: 'Foto tomada',
    decidedAt: 'Decisión',
    location: 'Ubicación',
    photo: 'Foto',
    photoOffline: 'La foto se ve con internet.',
    locationSource: {
      GPS: 'GPS del controlador al tomar la foto',
      MARCADOR: 'Aproximada: coordenadas del marcador de la hilera',
      NINGUNA: 'Sin coordenadas',
    } as Record<string, string>,
    status: {
      CONFIRMADO_POR_ESPECIALISTA: 'Confirmado por especialista',
      CONFIRMADO_POR_IA: 'Confirmado por IA',
      POSIBLE_PLAGA: 'Posible plaga',
      PENDIENTE_REVISION: 'En revisión',
    } as Record<string, string>,
    attrSat: 'Imágenes © Esri, Maxar, Earthstar Geographics',
    attrStreets: 'Mapa © Esri, HERE, Garmin, © OpenStreetMap',
    specialistNote: 'Con tu usuario la app muestra las alertas de plaga para ir al lugar. El monitoreo lo hace el operador.',
    notFound: 'Esta alerta ya no está en la lista (pudo ser descartada).',
    cardinal: {
      N: 'norte',
      NE: 'noreste',
      E: 'este',
      SE: 'sureste',
      S: 'sur',
      SO: 'suroeste',
      O: 'oeste',
      NO: 'noroeste',
    } as Record<string, string>,
  },
} as const;

// ------------------------------------------------ etiquetas de estados (con texto, no solo color: RNF-09)
export const ROLE_LABEL: Record<DeviceRole, string> = {
  CONTROLADOR: 'Controlador',
  CAMERA_1: 'Cámara 1',
  CAMERA_2: 'Cámara 2',
};

export const MODE_LABEL: Record<CaptureMode, string> = { MANUAL: 'MANUAL', AUTOMATICO: 'AUTOMÁTICO' };

export const LATERAL_LABEL: Record<LateralCode, string> = { LATERAL_A: 'Lateral A', LATERAL_B: 'Lateral B' };

export const LINK_LABEL: Record<CameraLinkStatus, string> = {
  DESCONECTADA: 'DESCONECTADA',
  EMPAREJANDO: 'EMPAREJANDO',
  CONECTADA: 'CONECTADA',
  INESTABLE: 'INESTABLE',
  PERDIDA: 'PERDIDA',
};

export const QUALITY_LABEL: Record<QualityStatus, string> = {
  CAPTURED: 'EVALUANDO',
  UTILIZABLE: 'UTILIZABLE',
  REPETIR_NITIDEZ: 'REPETIR (NITIDEZ)',
  REPETIR_EXPOSICION: 'REPETIR (LUZ)',
  ERROR_CAMARA: 'ERROR DE CÁMARA',
  PENDIENTE_REVISION_TECNICA: 'REVISIÓN TÉCNICA',
};

export const SLOT_LABEL: Record<SlotOutcome, string> = {
  PENDIENTE: 'Esperando',
  OK_PENDIENTE_ARCHIVO: 'OK · llegando',
  OK_RECIBIDA: 'OK',
  RECHAZADA_CALIDAD: 'Rechazada',
  ERROR_CAMARA: 'Error',
  SIN_RESPUESTA: 'Sin respuesta',
};

export const SEQUENCE_LABEL: Record<SequenceStatus, string> = {
  CREATED: 'Creada',
  COMMAND_SENT: 'Enviada',
  PARTIAL: 'Parcial',
  COMPLETE: 'Completa',
  INCOMPLETE: 'Incompleta',
  CANCELLED: 'Cancelada',
};

export const SESSION_LABEL: Record<SessionStatus, string> = {
  DRAFT: 'Borrador',
  PREPARING: 'Preparando',
  READY: 'Lista',
  ACTIVE: 'Activa',
  PAUSED: 'En pausa',
  CLOSING: 'Cerrando',
  CLOSED: 'Cerrada',
  SYNCED: 'Sincronizada',
};

export const PASS_LABEL: Record<PassStatus, string> = {
  READY: 'Lista',
  ACTIVE: 'Activa',
  PAUSED: 'En pausa',
  COMPLETED: 'Completa',
  INCOMPLETE: 'Incompleta',
};

export const INCIDENT_LABEL: Record<IncidentType, string> = {
  CALIDAD: 'Calidad',
  DESCONEXION: 'Desconexión',
  BATERIA: 'Batería',
  TEMPERATURA: 'Temperatura',
  ESPACIO: 'Espacio',
  GPS: 'GPS',
  TRANSFERENCIA: 'Transferencia',
  SINCRONIZACION: 'Sincronización',
  SOPORTE: 'Soporte',
  OPERADOR: 'Operador',
  OTRO: 'Otro',
};

/** Formato de bytes legible (GB/MB). */
export function formatBytes(bytes: number | null): string {
  if (bytes === null || !Number.isFinite(bytes)) return '—';
  const gb = bytes / 1024 ** 3;
  if (gb >= 1) return `${gb.toFixed(1)} GB`;
  return `${(bytes / 1024 ** 2).toFixed(0)} MB`;
}

export function formatPct(value: number | null): string {
  return value === null ? '—' : `${Math.round(value)} %`;
}
